<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dmc</string>
		<string>DMC</string>
	</array>
	<key>name</key>
	<string>Galil DMC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\'.*$</string>
			<key>name</key>
			<string>comment.galildmc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>REM comment</string>
			<key>match</key>
			<string>^REM.*$</string>
			<key>name</key>
			<string>comment.galildmc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string.quoted.single.galildmc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Built in variables</string>
			<key>match</key>
			<string>_[A-Z0-9]+</string>
			<key>name</key>
			<string>storage.type.galildmc</string>
		</dict>
		<dict/>
		<dict>
			<key>comment</key>
			<string>Control Commands</string>
			<key>match</key>
			<string>(ELSE|ENDIF|END|IF|P2CD|P2CH|P2NM|P2ST|REM|TIME)</string>
			<key>name</key>
			<string>keyword.control.galildmc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Commands A-J</string>
			<key>match</key>
			<string>(A[BCDFGILMOPQRSTUVW]|B[ABCDGIKLMNOPQRSTVWXZ]|C[ABCDEFIMNORSW]|D[ACEFHLMPRTV]|E[ABCDGIMNOPQRSTWY]|F[AEILV]|G[ADMR]|H[MSVX]|I[ADHIIKLNPT]|J[GPS])</string>
			<key>name</key>
			<string>keyword.control.galildmc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Commands K-P</string>
			<key>match</key>
			<string>(K[DIPS]|K[123]|L[ABCDEILMSUVZ]|M[BFGORTW]|N[BFOZ]|O[ABCEFPTV]|P[AFLRTVW])</string>
			<key>name</key>
			<string>keyword.control.galildmc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Commands Q-V</string>
			<key>match</key>
			<string>(Q[DHRSUZ]|R[ACDEILPS]|S[ABCDHILT]|T[ABCDEHIKLMNPRSTVWZ]|U[IL]|V[ADEFMPRSV])</string>
			<key>name</key>
			<string>keyword.control.galildmc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Commands W-Z</string>
			<key>match</key>
			<string>(W[BHT]|XQ|Y[ABCRS]|Z[ASNPD])</string>
			<key>name</key>
			<string>keyword.control.galildmc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Labels</string>
			<key>match</key>
			<string>#[A-Za-z0-9_]{2,8}</string>
			<key>name</key>
			<string>entity.name.function.label.galildmc</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric Values</string>
			<key>match</key>
			<string>\$*[0-9A-F]+</string>
			<key>name</key>
			<string>constant.numeric.galildmc</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.galildmc</string>
	<key>uuid</key>
	<string>d9658f70-bbc5-11e3-a5e2-0800200c9a66</string>
</dict>
</plist>
